// src/services/pdfGenerator.js
import jsPDF from "jspdf";

export const generatePDF = (transcript, scamReason) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleString();

  // --- HEADER ---
  doc.setFillColor(255, 0, 0); // Red Header
  doc.rect(0, 0, 210, 20, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("SENTINEL.AI - CYBER CRIME INCIDENT REPORT", 10, 13);

  // --- INCIDENT DETAILS ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  
  let y = 40; // Vertical starting position

  doc.text(`DATE & TIME: ${date}`, 10, y);
  y += 10;
  doc.text(`DETECTED THREAT: ${scamReason}`, 10, y);
  y += 10;
  doc.text(`SEVERITY LEVEL: CRITICAL`, 10, y);
  y += 20;

  // --- EVIDENCE SECTION ---
  doc.setFont("helvetica", "bold");
  doc.text("EVIDENCE TRANSCRIPT:", 10, y);
  y += 10;
  
  doc.setFont("courier", "normal"); // Typewriter font for transcript
  doc.setFontSize(10);
  
  // Split long text into multiple lines
  const splitText = doc.splitTextToSize(transcript, 180);
  doc.text(splitText, 10, y);

  // --- FOOTER ---
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.text("This report was automatically generated by Sentinel.ai real-time defense system.", 10, 280);
  doc.text("Please forward this to cybercrime.gov.in immediately.", 10, 285);

  // Download
  doc.save("Sentinel_Cyber_Report.pdf");
};
